---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authz-service-secret
  namespace: sa-p8-dev
spec:
  encryptedData:
    JWT_SECRET: AgAeg55Atg0fdwZR9xAcGYdhfWr+SqI3JhQ9a1RaHxdUdjBxAZmCZbK6yL+2Xh2ihjxvucDXhREg01xng9i9I/O51Qwy8rVDMhwmwO+AcK5C97yLL7n2nXqes5jWLM1JpuvTH2TmcY00IqDQNRcuYsP0Ox//oZ8y6NLLfHf8CcYS6g/vDzKyumAwMO/qEbzkdLvKGSx72i5uQ7bwUrzao76EsoSdNi4plOA6Waso8JG135nsEM+a2I17CMgq1Iw6NjBoQAkG2+8qaXfFRZP7a7CHodDaCswP80aRrZkFSZaFDP3nJas29eV4TEuFxAOc+fJddQt/QBbRsnuobvJ2Up9mZ6UpgmAbyP47uzr3951dlaHr+Be6lT+ZJUDc7eBHHevJJO92OcwDlSQyKZ79jVvcDa7VFqFn9i417qG3VScYts0BUo/WLILJJ8tpRE4IUw8Kex1jjOPV06KaaQ/LM1owjDucjmZ3wZR029gWx0N7kQUPZP2PA8M+UMlNpAqVwhjjoUF3qqHtaT5UhaQ5h3zb3MiYY3OQ8qhYHY9gXve742QWkh2XAVbQklcs4zVUYB4ZuBrYV7dZDbHt9TRNLleTy8GMuYvEQGkV5k6x9vanrGX1hXR6N0NABv+H3ilFeo2soRcH6o+fXBlGruzix3cqS/nlSguob1EKj6QK0enjsfvHq7alSlLld5wQ36/4Vzd3Wlo9atA5hOFkeFDsKxse73HEKf20kXRawZj26acqLJUXLcc7rUxc
  template:
    metadata:
      name: authz-service-secret
      namespace: sa-p8-dev
