---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: datos-rabbitmq
  namespace: sa-p8-dev
spec:
  encryptedData:
    rabbitmq-erlang-cookie: AgAVO6VwgGVwrF/D967j4v/yTKUOug52pGm/urnrs1WZJywSrQDJLluB3kA6a/SGPJrcKjHWf2Z7NYLZmyOrRH8THJF1gcxUVeE28HO1ooQejWvdPnrHfbM2akbgzZ83zA8HeYO6yGyVW2i/nqZOY1WywyKLwXSKze9yCjSSZ19NkoWcw4w7AntTEmemFTng5mO2wFLrDYOP0nNjxrAEi1m86yLHRfQIulJIwgLahcIFLIk0OL4GwmiJW+xkzdadQtRwT9cv5hGsmzd+fAyRBWkqKTjX/posGq44X9oL+zGKaP+zNukbHviLa8goZviwG+NTiIJfQigT0eo/GKEf0UkdFdW0puj5GO8hUICCkLkp9LcdQO4eLMPswBKImkS0k2A68HWIzyyPacFot0blpzpJ9H+4fc+HMB08ulvoi4klYXZEmf8x85YMVYC8PaNZW8gz+K+D9ANXiGCmaoGTCRUWbpy9/7giKkzIjfAHGCBIDf4bVhTlzwDBM4HxDLC4zm82heFFiD0rp4lcZx+cBIcP0aF83O6n6Qxu0FcZ1uUu9fKeZ+IAbuoXMJdVJM86U74Xj1Hd8nCWMVfSXiwgRPtQpK05YVYbnMYktsn3zcn1gbCvGvSOPzokcufGn2nbSKYJPjFBsUb4QeMOLTMjuARe+xy2r1jeL0zeXfy2a/S3y5BZfhgiPQy1IYU3DU7fIF6ZF1qOP1mGIZyQx0lE5X7Pnf3f1wxov36pams19/5Pn7MIErwM3OX4
    rabbitmq-password: AgAeoKRTGpTTf5dKA1a3TN1xHYPOQludSJdckyOMK/5yZI1hkJtusHjD6YZMY3RMa+I5/02QAaHUamRzuD11We++Zfyvwbbw1KF8X96iOTD1qqowPb+oeC6Wo4jR5a5WPcp9FGbiPwP/PVTcwNbYuIIJ89ANcu5OifDa3XF5CFm7Xu3sE8h5rTyhiFQpZghjMnKwVtUJE3AFhLf3/j4bhX5dGDG9qiTkXRFRlfc9biRDWAY9yCTrrMXhxm0jdP5DZcW77u1EEFCcPk4o7FlcMOMmRV5LKyt36Qh4Kn2so1bVsysIhkEZyGLru+Yy5k8Qfl9xKopGLQ0hjS7yxgojFpgFSK0LnUXbaaJTQM0fpauNRaEBP2uEy1j/bueHtacqi69x3HYYV0Yy+LY3DvLrJC671rER9CsWh+rMnOSP2tXrE8lrC76sqcCmQHuGRG2xMe34rQkEcrNACRS0/8VUdXa6VkN17zeq3wX4oSQ+2QVftBV/e05enj3Ix8GXLciktvvhJvoOaRYVFz0ISeGCv+ULHhpAsr6Kl0bNByQ/e2l2GXBmnm6PKITJAZst9MJDa9IwvBHa/jzzRuSYnueuQyTa17CJ4dE1+Fp0SuoZbrBtX6rAr9DEPQhpx1k1EVkWatR88k6uiIyEPQEXzY0B+bTLsDQwYAMlGUM20QSFcywnoWZTCX9GpHhTHPPjx3apyjfXS9vv7BsWWRKKk8Ym6MvlpuPkEA==
  template:
    metadata:
      name: datos-rabbitmq
      namespace: sa-p8-dev
