---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: datos-postgresql
  namespace: sa-p8-dev
spec:
  encryptedData:
    password: AgCddhk1tOvrbCrTS5zajRfJW/hZZ9EqWBPF/JZFbLGbEw1EBJ4rroGiRfaXz5ScU7GtriUJg+70DLuQ+Q/39gI+bWdZMSXKNlKui0TtOAImR/cq99jmW84HKlOHzhgK0LqXfWBJw1/1wOXlfkQqstnSu47X6nOESJBoC93KK0VvUV94dY+DlYAUl8XDrmkSZ9WRxN8QFQqbPT8L1ZaMrA5SWNU06JZxUH3F8oku+anPr/1fTPmdaPjgkcaZ2dxF4ze3pMvMHY8ofiRGQddk6qTxGinA739V5dz13AwLNy9w6RNZLsqhc4R4YkX+RM/+cVRHN/x9KLOkSmS3VDRU+V1fwUFcqTcA00d2RKcQF90a51COk4MVVT/mYfGJ/Vqo4EoPjJoaLLO4l+HC7/Y0ZPKaalHzt8Utk0G+PFqdzKCUoyubJiRlAp2uoL+nJLllRhpNlhG/za2NksF+1RH5g/mFbDOHd5QQ8+UidJkLNsXkwiS+FyVycHXmwBJnW/xs8kRsmnvzPZm4+2z4Nqo26aH/Jb+60YvF8LcPMy3HTMVti/MoDC+qJ1sAZp7JOfcJqnJxa8NZOHu7lMVkzC/Pq5EE5wZq10hPj7TOOqfQ+CqOejax8lbvoJFVkH5YFwOAX/sU64Ennp8UMRfSsClQa4tO+RHbPGIgZGDg8fHSQc3gWYzO48GqtrhPbhXXA7Jqk9/dtpXTll47e4yv7WzyMch8IcfHZA==
    postgres-password: AgBqSfzUJRvnDiyIH0r602Dbh/Md2nSQtXGIpsrLubY3RWth1OTaKuvE+rzjfWHte6pTYTSsHlbW3FJcqtcReBHB0YMwQjzGTNYqngUr3oE/218dq9QEwnW7uyNOaXMXLjQfW3r5NUR+dRTG/MvbcQN94dhl7xsaVM5cC4ZfUJ+zr0KgXTz1+RH11RNAofiVlcovRqGZkACzWVLvEkNRLixGDhK3mY5cc9NItDTdt+nRXoXa9QFQS28QmhptA80/GA0zG1Xn4uim8N1rPY2i78m3pWNTy+Mhg5d0khOqkdUVd6HuHyOYTNW/9FtRvCDSyaHfpKZ9MUxZLpvjJitfBChi7A5AlNLVWeCGUk8abCEB96Myx7VMHe86nig+tyKg9FVAzx/tfOapYSFgxwMu/LjfYBwhOWOFU8BltGsM+Xn6bO7I1KkZX8NQTXTrBWT6CPgoj73xnZEviItB79CI18iWzxSLq63axRMypuGOpqTFkpCf/ZAzQzvlHFJn+zn1P7V4e6KH1PGEcTIKcw2bv88WJy/+FVNJliXFIIQlHwTvicMHJf/vOTCEi1/+YcEP85TIEFBlknxGy0dTaqdA45MbobVvJBT3mbSXpbKgjnGvdMxzG3o5QT4ZU+su2cH9EWrPJkl4LRNnbDywbqcmxwTUFbXzkJP9AbdnBfYTBWVWTZDLGJveXxZEw+cTvG57W8L97OLU/32e6gbnF9CEKDi4bXwAUQ==
  template:
    metadata:
      name: datos-postgresql
      namespace: sa-p8-dev
