---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: datos-rabbitmq
  namespace: sa-p8
spec:
  encryptedData:
    rabbitmq-erlang-cookie: AgAOfpDFwrhc7RZc52nzMO0Bcz/V7f6ycA0q3vkuipEwot7ZfHSfUIBRC/7byovE6eYLojXgaVDurLofSm9TWilAJO8ei3KRA/JJwOG3S8nrPXUNTMpU+f6mro9lMufbwOKqIwtVRjx34dJrXtpnFu7JKyMgcIqc+tFKtChJA39Z5+mTaev7BoTQwwdmeVUjG+NblHKfz2jFDLnqb3wQ0A1ZiiFiyG3W9edKlSz5HpGElnKDz1NH7HOwzwIsy8/FSa0N/Pfp1u5YR4idynN5g8pxjt3RCTE4nE0Ph2nhZpLBm6Wkb6pJrFZmeNtS/UEt4YYihaFow+1B9zvI3X0K2M83qBs2z1FWwqK0RZN9Ppul92z9X8k9EiHPl0YQc995ot7l/aqOdtYfiVJk/4/NJwEFc6rRt4vX3+tFzPTpsFsUIfPrdiBUmB2zCkwcL3/bit/MQIqaa12ZIZv+Psyx51jApHVYJ5mHrryvBhtIjOXiQpKR0CzyHmj3BXI9N6qC5rLlsnVAN9BZbDVQqujCdnmYpJ5RKUZARbszDtmm2SRbHjARj8h0VpQ9mBZIO41J4na7OxxmxSqT8U7x6aHb1pblkqhstWbRfGL0nf4vpG7ZH/nn5iILzhlfIBlPPWfqK7OavRayJ24s4ty+0f4m5kXtJUe9HMqabhSsbaYexmZ+3qvMSuvp/D+i8t2d20qWY57bB4mj0IEjMxVHCcoRlpBr4UWmnSdksuURzM9609U3mO7K1lbfnXl3
    rabbitmq-password: AgAwraGx8WTf/XkQq61H9RBVsagNr45ZcGaqV/hydT/MDfnw/AN440EQzB7wkSRsVn964GgMRhymaDdJvoizwa73/S7FeXNXcBjfd/fYoXDRPxSPi85J5aMPw7sx+fjDLWxafXFuV5SxMbcbVaqZLJ5/TqoX1RIrhZfsSxsV0YtJw9mF7XJAlZ5Y5/12Fk7Mx4+wFw2jEbVEbds6Z2vpqh7QawVYI6NJNSS0YB/hgItyDtvtyspRSo79Unn4c5s8D/o0+4woqS/y7hBo8GRi4sTL7tpXktOQgc2KyfBsJp5vzQqa67rtGbNVQijfXu3UQ5EkvUnATTym/8vErebJMUbGvfJ1PQ4Hnpk6+JEFZ/xdjK9W4a2aV5L8t0QP3SMYfY4p5arhXwTkecINEIomCReKw8jNaTIkddql7qAaZFcNtkqpqKluW9mdeqevab7SCeJ19Ng2GcKBdwGJfmr1x7YtO5++aDWaSNIqhlqtmTfpzsumUXlhlRbuSW9n3LbSw82HMMMfu2yfe7Yu2QrOCgbxss+QwRNov9weW5Vb0Q8TN+fWMOPZkiv/IcZxkLmVDILAs4AcVXDJXBGjAUxuD6mCzOMZ+H9GGwuki+t4qPHtxb0bJnBPZK8YfaIKK7+IKt35RqcO8IpxBeZvHa26ha2OVOUD5SjPz9BXkZZCXQVWZcEFapHZo1Pfyjl++ZnXBq8UMKil/d0vTRWkv+/EaXy6ayv7+g==
  template:
    metadata:
      name: datos-rabbitmq
      namespace: sa-p8
