---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authz-service-secret
  namespace: sa-p8
spec:
  encryptedData:
    JWT_SECRET: AgAFBAPRBzCLWVvkJ8fDgWGUJa90RLFboYk/6qJIOv/H6hW+i1PmPMp85wAQJcl7wSL23DCUHjlPpLj3dkXjAmkbQFBl4IHKqFgKzdI+gQp75b7D0H7Gsjy8CzqNGohT/npCAz4UxMoywlOJJ+RZ+slYZFxRTuEsqVFUHd5p7luxIRNs3QMVZJgaHCwhTa1eKUj5sbsGJLHnTB4/oiKVsvKV0AdIpre5QYCbBlEvxzJHiTuz3fWmVqX71z3rEk9d0tu4K5pUeAQ9kOXwQnw1BQF/2/L+r3ucU/AgFskskfB5QOaB4itmmXt+LnZ9h1Ks7BHW87giiKxnz0wiGViWxaAgJ56H2wZjoFtZDY0m1xjVKAQWqYrL9aOALcLRQIIV7wqOrMat6lkoM49jgwdP9g9gNbbI7D9E2o/0LJtfJIqG4q4a7ulXmOF4z35rX9nwmA2vgC4+HfTsCePoI94wueFvuOvMeShjQ6wEOwqG7YsiGWjs1uzsOZgL1nM+C1N5WmbuGBxzch6MwRjO5pwVICtZU0Hjx9YpOMzeN+blPR08SMzpV1AClftAp07rU+26Fy/vAioW4o+WnWs/c8FXYR/ITrwNRdfRURJggTVvuA6aYhaKyXTvehxBB33FmKS/icT2/v0FXiU/EGYy4mUjP0ezskhDbghN1d5h5LQPdVsZvcCekaCZyvG8+rtKe2nByD4/B9zmBAnlfCyVQ8KBJUl5UO14ccyNa03FPZgY4fBe+ke4Vw5nw/wL
  template:
    metadata:
      name: authz-service-secret
      namespace: sa-p8
