---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cronjobs-secret
  namespace: sa-p8
spec:
  encryptedData:
    BROKER_URL: AgAPtl/3BssOX96lwZBSp7S8OOCMUc5q9tboXa1E0btooC9mLgcr3BYjZl7IoduiflPtmNMetKqDfN5JUy99kcJbp1pcTsLoItEDXfMuvY9zgpIySLBqeyh4tePqZvdrB5n1d26OZyeWB/Kc0OzfGB/5HqqVaNqul8SObPwe25tqWWqkMrDwFVfnl0qOMvMPxT++9M6+8KIolUd9fESMI9p0hDITkfW727zjnB/VmoL4AIErIw4TSC2eglof3tCVnqmf1VZhC1qkOTXkyBiwZGYunBXgxv7tNmAV9/zzJx/AgNFa6rHS7BVeTQP+k2TbqTVdGxFXo5qVlb7LvPrJgvb2mMUyCYsOAvhYkxFmTyzcaQ/1b80e/AzuxfUNbWNGZYsg2GmcM4E2HPMxdyU0DBcu30aFZdWLUDxP/tOxT4Eq9nZl1KwbXalUJD/hoQhQaOqJJ3MH/dWGkhKnxxdFA9qOT9iFwHItVI2th4exXku4G8/SiYN0z2bMYcDCnUoUXn/dKhMY+iYH4L7IC/YOcgXpn3iZBmbh0HkRtIkboOKPG+q2Nk5UDHzX9pdxvFn02+MA7dkns5ap7ed1nkDYJjBCzZsMNY47U6T5dPIIGWrGGrp1S2HS20JfIv5JE988d36vTIhdCeOb5CFT+I4f0hLJXOwnhGP3YHBRM8EuO54tWQDehKwkBWaIuJjroy+efLlPQHIsSlXCWT9Etx9vtXH0yrSVIFfB3kiudxdLKvDd4ByEmbVebwlDIHMXofo=
    DATABASE_URL: AgBELydYrSWg0a2mLlMq/xxIWipAPZSeBzQlHbBzEI0tNklHDvCU5MmzEfeObwEbyjEM+uyCFj3N+DvAprEgGfg+380YZAmLejw+mEqpGW5Roc5dHGLC3K8St4IQVJRU5nvftBuocywBLSAqupKTiVU/XXtF7XWXvm16bW8Hb1GLAUvWFs1iZRCheDG6JxAB1IL6fFM2GcF8qCxd/uyYV8Ibyx9DoctUjCf5/BPIPWkN2AO9AWMkmxNVtxzP98cVtOCkkpZNj/IAWN+aRNqWu9v+kz+KX2sykrRNf9Lpda6zPfl1Ech+bEj+6642LT0tFKotcoRT7x1L+jrsUdqEqTEYc/tliDBXmLU7Fa3uZAfBhq/T0/X8ud4N1SZpsgr7t6Jov9XDV1eTLhDpXYjTe2h0RqQJ86py6JbUwgkMcB9CILb5/iF4JSFJka3o9MLVL2w9SzEgVb9rGzas8Ut8zlwkLGI+lxjTJlqkeB9o4G7l64oBW8UzhvkSh7KxBapTZhp14S7hklBQrMpOmorExmUK4ktnU6n5urw1UqDUWmg4ldayaAfdt7ZN161cH+JZZCwOHgR6vncgEfDMdvqODjtGmVscMFFzF+daBxgDvsgyae+tOb3IaZLPZhh0APeR+h93LM7KUpp7E5qVz905qGqxxS7FL03xT/M8wGmARsvewqn066xMZzKsJ0rDDE5K/qgav4JX+FzVnaeoiJFMpjwESDfLJFOUIvqSTJadDtxIhTemo/VckDyLTt1XifOecRwiCDiN4Tz5zXZO
  template:
    metadata:
      name: cronjobs-secret
      namespace: sa-p8
