---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: datos-postgresql
  namespace: sa-p8
spec:
  encryptedData:
    password: AgCKbCi4x1dzoWo2JQL2PiOhEM7OTUVIsOP9WUrd5h2GTwoDQAwtEsqSjQM05gcKluAHmOctFx2fCxmbCtFPYZNpZvDanGlvwmoUaQjD/DfO4AXEiIYYAWZTBwn2Tkh5rIQ6+J5Rrkjy+hJfGzU4vC+SRRyKt0NRacUzIghseTDc0xNE7lG8/QafovJXWlyz+bBD1y/w8GDJRWh8Nv5WtVAhtlI1iYWVSgUOYyadxQzOi8nuk4M3uf04LwR2J+IRb3SRCblrGRSL7yGHwvQg+8ywYnYZl76A1E8xzXDOaevyP+JegOknKZo70DBo8A9a/Paik4+XWyUkGd3HQnTYR9+bei/EE80EMutm1MaevgxlrQw/3JERv1kDgMcoPOcFJ2W5qtxj26dCwfBrFs+dHP+A69gYdUGKU3zGtCpRRpcHvmso4qk/B3Cv40oaKTrfdcOSC1jMCm1x9TS8d+TAgX6A4GXw1cX7boOT823ZqFa/FP0Z3aq4TYtF+kqW8A9AdwAT5yWYeArOBbMMA8FV7i9zBvpU3XJlvgYN86wq7XsrirkbGdF6u2OxJMahrnG6fFMLt0POegg9thMxTAFVNq5pqa1Jsx3je7pk6d5CoiAiDszlcYJ02CbLCgFHMqi3PrluHu6DIEZM/LhFnP+SXu4dXz1Rh+EO1MEDDw51GQsT/wHy/Vb2wNRT71GqIScoD856hltrnncWPVJ8qPItjBNO7AWiQA==
    postgres-password: AgCgVyjQI7mGLVTtUVrOBIg5ajL8gl+ZO1HIDxPCDYGTPANm0f/SyKJ8X6GObFb/JY2wlnUXK7mace0ReEasnSS0ubd/9V8e8XcR1OsuNG0/gi9NornqnvIR+KRmjkXk6v4czVs5z2Q/vd7gTVJlJf2amYber+jXyAO7xw7IojFWPE3A+8pnDgCkYAFjE1OhP9L+xxXKeC3xL+aaWbzaY+4VxhkesgVzawEchXqrtjp7TDb50reyMkNuB3Q/9z6ldQby8q4AoecdB9akeqWFnMJoGR1nBFm676MWXpkee1Zt+evSXlAx6lDWyPH2EK6XcA/r1/WMtJOcZaZTi9ZgP4q4LZN78odpLKQvpH4+UGEI+P2BAEhVkcWw3gARjUZptpgotWpFgF/Z2trW4LphyQVSDFbhff7uSmHePf5JJlLAyvfXyr+wjizifWJI5k/YQiOSMmbK6X4eJpl8QuuCuBetMGPAceSMYDd83VxlmV9mkvpbi6DuzQKKLQ/IUB3USRgvrFPIru9nI/5/W5vUqoBU62i8toTXgssy5Fzb/Od3Wx0MHqq0SG8TdjiEXmNGP+l5KNexb+z0BPHNY2R5s3dOf4H+/SRAEYsn1sE879909GWbG3RXwHW0LN58mQqnSSjqQChoJJsQ+2og+rMZMeaLyOXXVXPJ7SzLt71nOS5+5xAzO8Fb7+WBFX2A7ifXNIGf2UY6jsbYGqIVAt5mSE2HV2ykCw==
  template:
    metadata:
      name: datos-postgresql
      namespace: sa-p8
