apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: git@github.com:jaguzaro/Practicas-SA-B-202201395.git
      targetRevision: main
      path: P8/charts/gateway
      helm:
        valueFiles:
          - values-dev.yaml
          - $values/values/dev/gateway.yaml
    - repoURL: https://github.com/jaguzaro/Practicas-SA-B-202201395-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: sa-p8-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
