apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: politicas
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:jaguzaro/Practicas-SA-B-202201395.git
    targetRevision: main
    path: P8/policies
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
