apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secretos
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jaguzaro/Practicas-SA-B-202201395-gitops.git
    targetRevision: main
    path: secretos
  destination:
    server: https://kubernetes.default.svc
    namespace: sa-p8
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
